class RusturesError(RuntimeError): ...

class CostL2:
    def __init__(self) -> None: ...
    def fit(self, signal: object) -> CostL2: ...
    def error(self, start: int, end: int) -> float: ...
    def sum_of_costs(self, breakpoints: list[int]) -> float: ...
    @property
    def n_samples(self) -> int: ...
    @property
    def n_features(self) -> int: ...
    @property
    def min_size(self) -> int: ...
    @property
    def is_fitted(self) -> bool: ...

class Dynp:
    def __init__(
        self, model: str = "l2", min_size: int = 2, jump: int = 5
    ) -> None: ...
    def fit(self, signal: object) -> Dynp: ...
    def predict(self, n_bkps: int) -> list[int]: ...
    def fit_predict(self, signal: object, n_bkps: int) -> list[int]: ...
    @property
    def model(self) -> str: ...
    @property
    def min_size(self) -> int: ...
    @property
    def jump(self) -> int: ...
    @property
    def is_fitted(self) -> bool: ...

class Pelt:
    def __init__(
        self, model: str = "l2", min_size: int = 2, jump: int = 5
    ) -> None: ...
    def fit(self, signal: object) -> Pelt: ...
    def predict(self, pen: float) -> list[int]: ...
    def fit_predict(self, signal: object, pen: float) -> list[int]: ...
    @property
    def model(self) -> str: ...
    @property
    def min_size(self) -> int: ...
    @property
    def jump(self) -> int: ...
    @property
    def is_fitted(self) -> bool: ...

class Binseg:
    def __init__(self, model: str = "l2", min_size: int = 2, jump: int = 5) -> None: ...
    def fit(self, signal: object) -> Binseg: ...
    def predict(self, n_bkps: int | None = None, pen: float | None = None, epsilon: float | None = None) -> list[int]: ...
    def fit_predict(self, signal: object, n_bkps: int | None = None, pen: float | None = None, epsilon: float | None = None) -> list[int]: ...
    @property
    def model(self) -> str: ...
    @property
    def min_size(self) -> int: ...
    @property
    def jump(self) -> int: ...
    @property
    def is_fitted(self) -> bool: ...

class BottomUp(Binseg): ...

class Window(Binseg):
    def __init__(self, width: int = 100, model: str = "l2", min_size: int = 2, jump: int = 5) -> None: ...
    @property
    def width(self) -> int: ...

class KernelCPD:
    def __init__(self, kernel: str = "rbf", min_size: int = 2, jump: int = 1, gamma: float | None = None, gamma_policy: str = "exact", gamma_samples: int = 10_000, seed: int = 0, backend: str = "fused", max_gram_bytes: int = 536_870_912) -> None: ...
    def fit(self, signal: object) -> KernelCPD: ...
    def predict(self, n_bkps: int | None = None, pen: float | None = None) -> list[int]: ...
    def fit_predict(self, signal: object, n_bkps: int | None = None, pen: float | None = None) -> list[int]: ...
    @property
    def kernel(self) -> str: ...
    @property
    def backend(self) -> str: ...
    @property
    def min_size(self) -> int: ...
    @property
    def jump(self) -> int: ...
    @property
    def gamma(self) -> float | None: ...
    @property
    def stored_gram_entries(self) -> int: ...
    @property
    def is_fitted(self) -> bool: ...

def version() -> str: ...
def validate_signal(signal: object) -> tuple[int, int]: ...
def hausdorff(truth: list[int], prediction: list[int]) -> float: ...
def precision_recall(truth: list[int], prediction: list[int], margin: int = 10) -> tuple[float, float]: ...
def rand_index(truth: list[int], prediction: list[int]) -> float: ...
def pw_constant(n_samples: int, n_features: int = 1, n_bkps: int = 3, noise_std: float = 1.0, seed: int = 0) -> tuple[object, list[int]]: ...
def pw_linear(n_samples: int, n_features: int = 1, n_bkps: int = 3, noise_std: float = 1.0, seed: int = 0) -> tuple[object, list[int]]: ...
def pw_normal(n_samples: int, n_features: int = 1, n_bkps: int = 3, noise_std: float = 1.0, seed: int = 0) -> tuple[object, list[int]]: ...
def pw_wavy(n_samples: int, n_features: int = 1, n_bkps: int = 3, noise_std: float = 1.0, seed: int = 0) -> tuple[object, list[int]]: ...

__version__: str
